# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Toda/Udacity/VisualizationP4/PipelineHelper/gui/box.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Box(object):
    def setupUi(self, Box):
        Box.setObjectName("Box")
        Box.resize(196, 164)
        self.gridLayout = QtWidgets.QGridLayout(Box)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(118, 30, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.titleLabel = QtWidgets.QLabel(Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.titleLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_3.addWidget(self.titleLabel)
        spacerItem1 = QtWidgets.QSpacerItem(78, 30, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.frameGroupBox = QtWidgets.QGroupBox(Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameGroupBox.sizePolicy().hasHeightForWidth())
        self.frameGroupBox.setSizePolicy(sizePolicy)
        self.frameGroupBox.setTitle("")
        self.frameGroupBox.setObjectName("frameGroupBox")
        self.verticalLayout_2.addWidget(self.frameGroupBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.min2maxLcdNumber = QtWidgets.QLCDNumber(Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min2maxLcdNumber.sizePolicy().hasHeightForWidth())
        self.min2maxLcdNumber.setSizePolicy(sizePolicy)
        self.min2maxLcdNumber.setMinimumSize(QtCore.QSize(64, 24))
        self.min2maxLcdNumber.setMaximumSize(QtCore.QSize(64, 24))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setWeight(75)
        self.min2maxLcdNumber.setFont(font)
        self.min2maxLcdNumber.setObjectName("min2maxLcdNumber")
        self.horizontalLayout.addWidget(self.min2maxLcdNumber)
        self.min2maxSlider = QtWidgets.QSlider(Box)
        self.min2maxSlider.setMinimumSize(QtCore.QSize(0, 30))
        self.min2maxSlider.setMaximumSize(QtCore.QSize(16777215, 30))
        self.min2maxSlider.setMaximum(255)
        self.min2maxSlider.setPageStep(5)
        self.min2maxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.min2maxSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.min2maxSlider.setObjectName("min2maxSlider")
        self.horizontalLayout.addWidget(self.min2maxSlider)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.max2minLcdNumber = QtWidgets.QLCDNumber(Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max2minLcdNumber.sizePolicy().hasHeightForWidth())
        self.max2minLcdNumber.setSizePolicy(sizePolicy)
        self.max2minLcdNumber.setMinimumSize(QtCore.QSize(64, 24))
        self.max2minLcdNumber.setMaximumSize(QtCore.QSize(64, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.max2minLcdNumber.setFont(font)
        self.max2minLcdNumber.setProperty("intValue", 255)
        self.max2minLcdNumber.setObjectName("max2minLcdNumber")
        self.horizontalLayout_2.addWidget(self.max2minLcdNumber)
        self.max2minSlider = QtWidgets.QSlider(Box)
        self.max2minSlider.setMinimumSize(QtCore.QSize(0, 30))
        self.max2minSlider.setMaximumSize(QtCore.QSize(16777215, 30))
        self.max2minSlider.setMinimum(0)
        self.max2minSlider.setMaximum(255)
        self.max2minSlider.setPageStep(5)
        self.max2minSlider.setProperty("value", 255)
        self.max2minSlider.setSliderPosition(255)
        self.max2minSlider.setOrientation(QtCore.Qt.Horizontal)
        self.max2minSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.max2minSlider.setTickInterval(0)
        self.max2minSlider.setObjectName("max2minSlider")
        self.horizontalLayout_2.addWidget(self.max2minSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Box)
        self.min2maxSlider.valueChanged['int'].connect(self.min2maxLcdNumber.display)
        self.max2minSlider.valueChanged['int'].connect(self.max2minLcdNumber.display)
        QtCore.QMetaObject.connectSlotsByName(Box)

    def retranslateUi(self, Box):
        _translate = QtCore.QCoreApplication.translate
        Box.setWindowTitle(_translate("Box", "Form"))
        self.titleLabel.setText(_translate("Box", "Box Title"))

